### PR TITLE
fix KenSuenobu/rust-pushrod#196

### PR DESCRIPTION
**Pull request by jbethune**
This patch adds 2 new variants to `CallbackEvent`: `ControllerButtonPressed` and `DPadPressed`.
These events are generated within the main event loop inside the `event.button()` handler. This event handler has been updated to distinguish between mouse clicks, keyboard presses, controller buttons and DPad presses. This patch also makes it possible to generate `CallbackEvent::KeyPressed` again.

Due to lack of equipment I could not test these changes for controllers and DPads.

### CODE REVIEW

**Comment by KenSuenobu** [comment]
I'm going to skip merging this, as the `rust-pushrod-render` project inside the `rust-pushrod` base now uses SDL2.  It will have the ability to pull in new events that can be used at a Widget; I'll figure out something for this later.

**Comment by jbethune** [comment]
Just to confirm that I understand this correctly: Because you now have a different backend (SDL2), the event types will change anyway and that makes my pull request obsolete?
If that is true, feel free to reject my pull request.

**Comment by jbethune** [comment]
Okay, I see you changed a lot (5 hours ago) after my last message. Now there are conflicts with my pull request. I will look into what changed later today and test if the original problem is still present.

**Comment by KenSuenobu** [comment]
Awesome.  The main code now uses SDL2, which is a huge change over the previous code.  I've been porting a lot of the widgets back to the library, so I'll make another big announcement once the porting effort is complete.  Then, I'll start adding new Widgets, and I might add a few CanvasWidget examples.

**Pull request closed without merging**
